var NOTE_NAMES=["C C\u266f D D\u266f E F F\u266f G G\u266f A A\u266f B".split(" "),"C D\u266d D E\u266d E F G\u266d G A\u266d A B\u266d B".split(" "),"Do Di Re Ri Mi Fa Fi So Si La Li Ti".split(" "),"Do Ra Re Me Mi Fa Se So Le La Te Ti".split(" "),"0 1 2 3 4 5 6 7 8 9 10 11".split(" ")],DEFAULT_COLOURS="red orange yellow lime green olive teal aqua blue navy fuchsia purple".split(" "),KEY_MAPPING="Q2W3ER5T6Y7UI9O0P\u00db\u00bb\u00dcAZSXCFVGBNJMK\u00bcL\u00be\u00bf",keyWidth,pianoHeight,blackKeyHeight,
startOctave=4,endOctave=5,mousePressed=!1,clickedNote=-1,dragNote=-1,notation=0,colourNote,colours=[],canvas,context,sample=[0,0,0,0,0,0,0],testNotes=Array(12),timer=null,userResponded,score,toneRow=[],editColours=!1,testMode=!1,selectNotes=!1,notesPlaying=[],players=[],notePlaying=-1,audioContext,gainNode,pianoTone=!0,octaveTolerant=!0,useColours=!1;window.AudioContext=window.AudioContext||window.webkitAudioContext;
if("function"===typeof AudioContext){audioContext=new AudioContext;gainNode=audioContext.createGain();for(var i=0;7>i;i++)(function(a){var c=new XMLHttpRequest;c.open("GET","Piano.mf.F"+a+".mp3");c.responseType="arraybuffer";c.onload=function(){audioContext.decodeAudioData(c.response,function(b){sample[a]=b;if(0>sample.indexOf(0))$("#piano").on("vmousemove",function(a){mouseMove(getX(a),getY(a))}).on("vmousedown",function(a){a.preventDefault();mouseDown(getX(a),getY(a))}).on("vmouseup",function(a){mouseUp(getX(a),
getY(a))}).on("vmouseout",function(){0<=clickedNote&&(cancelNote(clickedNote),clickedNote=-1)}).on("dblclick",function(a){a.preventDefault();editColours&&showColourDialog(getX(a),getY(a))})})};c.send()})(i)}else alert("Sorry, but Absolute Pitch is not compatible with this browser. Please try with the latest version of Chrome or Firefox instead. On Android, please use Firefox.");
$(document).on("pageshow",function(){if("undefined"!==typeof Storage&&null!==localStorage.getItem("colours"))colours=JSON.parse(localStorage.colours),startOctave=localStorage.startOctave,endOctave=localStorage.endOctave,$("#startOctave").val(startOctave).slider("refresh"),$("#endOctave").val(endOctave).slider("refresh"),$("#volume").val(localStorage.volume).slider("refresh"),$("#speed").val(localStorage.speed).slider("refresh"),notation=localStorage.notation,octaveTolerant="1"==localStorage.octaveTolerant,
useColours="1"==localStorage.useColours,tone=localStorage.tone,$("#tone").prop("selectedIndex",tone).slider("refresh"),pianoTone="0"==tone,testNotes=JSON.parse(localStorage.testNotes);else{colours=DEFAULT_COLOURS.slice(0);testNotes[0]=!0;for(var a=1;12>a;a++)testNotes[a]=!1}setVolume($("#volume").val());$("#notation").prop("selectedIndex",notation).selectmenu("refresh");$("#octaveTolerant").prop("checked",octaveTolerant).checkboxradio("refresh");$("#useColours").prop("checked",useColours).checkboxradio("refresh");
$("#optionsPanel").on("panelclose",optionsClose);a=navigator.userAgent.toLowerCase();0<=a.indexOf("firefox")&&($("#piano").css("bottom",$("#footer").height()+"px"),0<=a.indexOf("android")&&($("#tone").prop("selectedIndex",1).slider("refresh"),pianoTone=!1));drawPiano()});function getX(a){return a.clientX-$("#piano").offset().left}function getY(a){return a.clientY-$("#piano").offset().top}
function optionsClose(){"undefined"!==typeof Storage&&(localStorage.colours=JSON.stringify(colours),localStorage.startOctave=startOctave,localStorage.endOctave=endOctave,localStorage.notation=notation,localStorage.octaveTolerant=Number(octaveTolerant),localStorage.useColours=Number(useColours),localStorage.volume=$("#volume").val(),localStorage.speed=$("#speed").val(),localStorage.tone=$("#tone").prop("selectedIndex"),localStorage.testNotes=JSON.stringify(testNotes),drawPiano())}
function drawPiano(){var a=endOctave-startOctave;canvas=document.getElementById("piano");context=canvas.getContext("2d");keyWidth=Math.floor(window.innerWidth/(7*a));canvas.width=7*keyWidth*a;pianoHeight=Math.floor(3*window.innerHeight/(a+5));canvas.height=pianoHeight;blackKeyHeight=Math.floor(pianoHeight/2);for(var c=0,b=Math.floor(keyWidth/3),d=0;d<=7*a;d++)context.moveTo(c,0),context.lineTo(c,pianoHeight),context.stroke(),3!=d%7&&0!=d%7&&context.fillRect(c-b,0,2*b,blackKeyHeight),c+=keyWidth;editColours?
showPalette(!0):selectNotes&&showTestNotes();a=$(window).height()-$("#footer").height()-pianoHeight-17;c=$(window).width()/6;c>a&&(c=a);$("#noteName").height(a).css({fontSize:c+"px",lineHeight:a+"px"})}
function highlightKey(a,c){var b,d;d=a%12;a-=12*startOctave;b=Math.floor(a/12);a%=12;4<a&&a++;12<a&&a++;1==a%2?(context.fillStyle=c?useColours?colours[d]:"red":"black",context.fillRect(keyWidth*(7*b+(a+1)/2)-Math.floor(keyWidth/3)+1,0,Math.floor(2*keyWidth/3)-2,blackKeyHeight-1)):(a=Math.floor(a/2),b=keyWidth*(7*b+a),context.fillStyle=c?useColours?colours[d]:"red":"white",context.fillRect(b+1,blackKeyHeight,keyWidth-2,pianoHeight-blackKeyHeight),d=0==a||3==a?b+1:b+Math.floor(keyWidth/3),b=2==a||6==
a?b+keyWidth-1:b+keyWidth-Math.floor(keyWidth/3),context.fillRect(d,0,b-d,blackKeyHeight))}function mouseMove(a,c){if(null==timer&&mousePressed){var b=mouseposToNote(a,c),b=b.noteNo+12*(startOctave+b.octave);b!=clickedNote&&(cancelNote(clickedNote),clickedNote=b,processNote())}}
function keyUp(a){testMode?null!=timer&&32==a&&cancelNote(clickedNote):null==timer&&(a=KEY_MAPPING.indexOf(String.fromCharCode(a)),0<=a&&(a+=12*startOctave,0<=notesPlaying.indexOf(a)&&(highlightKey(a,!1),stopNote(a),0<notesPlaying.length?(a=notesPlaying[notesPlaying.length-1]%12,$("#noteName").text(noteName(a)).css("color",colours[a*useColours])):$("#noteName").text(""))))}function noteName(a){return NOTE_NAMES[notation][a]}
function cancelNote(a){highlightKey(a,!1);$("#noteName").text("");null==timer&&stopNote(a)}
function keyDown(a){testMode?32==a&&null!=timer&&(testNotes[notePlaying%12]?(userResponded=!0,clickedNote=notePlaying,highlightClickedKey(notePlaying)):($("#noteName").text("Wrong: "+noteName(notePlaying%12)).css({color:"red"}),stopPlaying())):null==timer&&(a=KEY_MAPPING.indexOf(String.fromCharCode(a)),0<=a&&(a+=12*startOctave,0>notesPlaying.indexOf(a)&&a<12*endOctave&&(highlightClickedKey(a),playNote(a))))}
function highlightClickedKey(a){$("#noteName").text(noteName(a%12)).css("color",useColours?colours[a%12]:"red");highlightKey(a,!0)}function showColourDialog(a,c){var b=mouseposToNote(a,c);0==b.octave&&($("#colorPicker").click(),colourNote=b.noteNo)}function changeColour(a){colours[colourNote]=a;console.log("colours: "+JSON.stringify(colours));highlightKey(colourNote+12*startOctave,!0)}
function mouseDown(a,c){var b=mouseposToNote(a,c);editColours?0==b.octave&&(dragNote=b.noteNo,canvas.style.cursor="move"):selectNotes?0==b.octave&&(testNotes[b.noteNo]=!testNotes[b.noteNo],highlightKey(b.noteNo+12*startOctave,testNotes[b.noteNo])):null!=timer?testMode&&(clickedNote=b.noteNo+12*(startOctave+b.octave),!testNotes[clickedNote%12]||!octaveTolerant&&notePlaying!=clickedNote||octaveTolerant&&notePlaying%12!=clickedNote%12?($("#noteName").text("Wrong: "+noteName(notePlaying%12)).css({color:"red"}),
stopPlaying()):(userResponded=!0,highlightClickedKey(clickedNote))):(mousePressed=!0,0<=clickedNote&&highlightKey(clickedNote,!1),clickedNote=b.noteNo+12*(startOctave+b.octave),processNote())}function mouseposToNote(a,c){1<a&&(a-=2);var b=2*Math.floor(a%(7*keyWidth)/keyWidth);4<b&&b--;c-2<=blackKeyHeight&&(a%keyWidth>2*keyWidth/3?4!=b&&11>b&&b++:a%keyWidth<keyWidth/3&&0<b&&5!=b&&b--);return{noteNo:b,octave:Math.floor(a/(7*keyWidth))}}
function processNote(){var a=clickedNote%12;null!=timer?(userResponded=!0,testNotes[a%12]&&a==notePlaying%12&&highlightClickedKey(clickedNote)):(highlightClickedKey(clickedNote),playNote(clickedNote))}
function mouseUp(a,c){mousePressed=!1;if(0<=dragNote){var b=mouseposToNote(a,c).noteNo;if(b!=dragNote){var d=colours[dragNote];colours[dragNote]=colours[b];colours[b]=d;showPalette(!0)}dragNote=-1;canvas.style.cursor="pointer"}else!selectNotes&&3>$("#noteName").text().length&&(cancelNote(clickedNote),clickedNote=-1)}
function playNote(a){if(pianoTone){var c=audioContext.createBufferSource();c.buffer=sample[Math.floor(a/12)-1];c.connect(gainNode);gainNode.connect(audioContext.destination);c.playbackRate.value=Math.pow(2,(a%12-5)/12)}else c=audioContext.createOscillator(),c.type=0,c.frequency.value=32.7032*Math.pow(2,a/12),c.connect(gainNode),c.connect(audioContext.destination);c.start(0);players.push(c);notesPlaying.push(a);notePlaying=a}
function stopNote(a){a=notesPlaying.indexOf(a);players[a].stop(0);notesPlaying.splice(a,1);players.splice(a,1)}function stopAllNotes(){for(var a=0;a<players.length;a++)players[a].stop(0);notesPlaying.length=0;players.length=0}function setVolume(a){gainNode.gain.value=a/10}function stopPlaying(){clearInterval(timer);timer=null;$("#playmode").val("start").slider("refresh");highlightKey(notePlaying,!1);clickedNote=-1;stopNote(notePlaying)}
function startPlaying(){stopAllNotes();$("#noteName").text("");if(editColours||selectNotes)editColours?(editColours=!1,$("#editColours").prop("checked",!1).checkboxradio("refresh"),showPalette(!1)):(selectNotes=!1,$("#selectNotes").prop("checked",!1).checkboxradio("refresh"),showTestNotes());userResponded=!1;score=0;clearRow();var a=Math.floor(12*Math.random());if(0<=testNotes.indexOf(!1))for(;testNotes[a];)a=Math.floor(12*Math.random());toneRow[a]=!0;a+=12*(startOctave+Math.floor(Math.random()*(endOctave-
startOctave)));playNote(a);timer=setInterval(timerEvent,4E3/$("#speed").val())}function changeSpeed(a){clearInterval(timer);timer=setInterval(timerEvent,4E3/a)}function clearRow(){for(var a=0;12>a;a++)toneRow[a]=!1}
function timerEvent(){var a;0>toneRow.indexOf(!1)&&clearRow();do a=Math.floor(12*Math.random());while(toneRow[a]);toneRow[a]=!0;a+=12*(startOctave+Math.floor(Math.random()*(endOctave-startOctave)));if(!testMode)testNotes[notePlaying%12]&&highlightKey(notePlaying,!1),testNotes[a%12]?highlightClickedKey(a):$("#noteName").text("");else if(testNotes[notePlaying%12])if(userResponded)$("#score").text(++score),userResponded=!1;else{$("#noteName").text("Missed: "+noteName(notePlaying%12)).css({color:"red"});
stopPlaying();return}stopNote(notePlaying);playNote(a)}function showPalette(a){for(var c=12*startOctave;c<12*(startOctave+1);c++)highlightKey(c,a)}function showTestNotes(){for(var a=12*startOctave;a<12*(startOctave+1);a++)highlightKey(a,testNotes[a%12]&&selectNotes)};